source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, "9.0"

#inhibit_all_warnings!
use_frameworks!

target 'APIClient-Example' do
	pod 'APIClient', :path => '../'
	pod 'PaginationUIManager', '~> 0.1'
end
